project:
  type: book

book:
  title: "Preppin Data 2022"
  author: "Avishai M. Tsur, MD MHA"
  date: today
  chapters:
    - index.qmd
    - 2022-01.qmd
    - 2022-02.qmd
    - 2022-03.qmd
    - 2022-04.qmd
    - 2022-05.qmd
    - 2022-06.qmd
    - 2022-07.qmd
  
format:
  html:
    theme: cosmo
    df-print: paged 

editor: visual

